from .wilds.tiger import tiger
from .wilds.wolf import wolf
from classes.pets.pet import pet
from .pets.cat import cat
from .pets.dog import dog
from .birds.hen import wild_hen
from .birds.stork import stork
from .interfaces.training import training
from .interfaces.flying import flying